{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "thekraken.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "thekraken.labels" . | nindent 4 }}
automountServiceAccountToken: false
{{- end }}
